version: '3.5'

volumes:
  mongo-conf:
    name: mongo-conf
  mongo-data:
    name: mongo-data
  redis-data:
    name: redis-data

services:
  mongo:
    container_name: mongo
    env_file:
      - secret.env
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-conf:/data/configdb
      - mongo-data:/data/db
  mongo-express:
    container_name: mongo-express
    depends_on:
      - mongo
    env_file:
      - secret.env
    image: mongo-express
    ports:
      - 8081:8081
    restart: on-failure:5
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  redis-commander:
    container_name: redis-commander
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    image: ghcr.io/joeferner/redis-commander
    ports:
      - 8082:8081
    restart: on-failure:5
